font_family      JetBrains Mono Bold
bold_font        auto
italic_font      auto
font_size        11.0
adjust_line_height 115%

cursor           #ffa028
cursor_text_color #000000
shell_integration no-cursor

foreground            #ffa028
background            #000000
selection_foreground  #000000
selection_background  #ffa028

color0  #000000
color8  #555555
color1  #ff433d
color9  #ff5555
color2  #4af6c3
color10 #55ff55
color3  #ffa028
color11 #ffff55
color4  #0068ff
color12 #5555ff
color5  #aa00aa
color13 #ff55ff
color6  #00aaaa
color14 #55ffff
color7  #aaaaaa
color15 #ffffff

hide_window_decorations no
window_padding_width 5
confirm_os_window_close 0

tab_bar_edge            top
tab_bar_style           separator
tab_separator           " | "
active_tab_foreground   #000000
active_tab_background   #ffa028
active_tab_font_style   bold
inactive_tab_foreground #ffa028
inactive_tab_background #000000

map ctrl+shift+f5 load_config_file
map ctrl+page_down next_tab
map ctrl+page_up previous_tab 
map ctrl+shift+enter launch --cwd=current
